### ISSUE TITLE
Request with GET/HEAD method cannot have body

### ISSUE THREAD

**Issue by sebastiendelorme** [rioam2/cors-reverse-proxy#1]
Thank you for this cors-reverse-proxy very useful.

I'm having an issue with GET requests : 
`TypeError: Request with GET/HEAD method cannot have body`

I think it's because of 
```
return fetch(url, {
            method: req.method,
            body: req.get("content-type") === "application/json" ? JSON.stringify(req.body) : req.body,
            headers,
        }).
```

We have a body request only on POST and PUT requests? It isn't?

**Comment by rioam2** [comment]
Thanks @sebastiendelorme for bringing this up. I think you're right in the fact that the body should be omitted if the request method is a `GET` request. If you're able to open a pull request with these changes, I'd be happy to merge it in :)

**Comment by sebastiendelorme** [comment]
Done :)
